spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
          javax:
            cache:
              provider: org.ehcache.jsr107.EhcacheCachingProvider
              uri: classpath:ehcache.xml
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinicdb
      database: clinicdb

server:
  port: 8080

app:
  jwt:
    secret: "mysupersecretkeymysupersecretkey"
    expiration: 1800000  # 30 minutes
    refresh-expiration: 1209600000  # refresh token (14 days)

# For springdoc UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Cache statistics (optional)
logging:
  level:
    org.hibernate.cache: DEBUG
    org.hibernate.stat: DEBUG