spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinicdb
      database: clinicdb

# Optional: keep H2 console for quick dev testing
# spring:
#   datasource:
#     url: jdbc:h2:mem:clinic;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:

server:
  port: 8080

app:
  jwt:
    secret: "mysupersecretkeymysupersecretkey"
    expiration: 1800000  # 30 minutes
    refresh-expiration: 1209600000  # refresh token (14 days)

# For springdoc UI (optional)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html